disabled = false
languageCode = "en"
languageName = "English"
weight = 2
title = "Ma.Ri.S Rigging"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/icon-light.png"
  # secondaryLogo = "img/icon-dark.png"
  # description = "Fluid power, absolute control."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Ma.Ri.S. Rigging"
   email = "michele@marisrigging.it"
   image = "img/icon-light.png"
   imageQuality = 96
   headline = "by Michele Cannarsa"
   bio = "Professional nautical rigging services in North Sardinia."
   links = [
     { email = "mailto:michele@marisrigging.it" },
#     { link = "https://link-to-some-website.com/" },
#     { facebook = "https://facebook.com/username" },
#     { github = "https://github.com/username" },
#     { instagram = "https://instagram.com/username" },
     { linkedin = "https://it.linkedin.com/in/michele-cannarsa-7687348b" },
     { telegram = "https://t.me/+393490867235" },
#     { x-twitter = "https://twitter.com/username" },
     { whatsapp = "https://wa.me/+393490867235" },
   ]
