disabled = false
languageCode = "es"
languageName = "Espa침ol"
weight = 3
title = "Ma.Ri.S Rigging"

[params]
  displayName = "Espa침ol"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/icon-light.png"
  # secondaryLogo = "img/icon-dark.png"
  # description = "Sailing Yacht Rigging di Michele Cannarsa"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
   name = "Ma.Ri.S. Rigging"
   email = "michele@marisrigging.it"
   image = "img/icon-light.png"
   imageQuality = 96
   headline = "de Michele Cannarsa"
   bio = "Rigging n치utico profesional en el norte de Cerde침a."
   links = [
     { email = "mailto:michele@marisrigging.it" },
#     { link = "https://link-to-some-website.com/" },
#     { facebook = "https://facebook.com/username" },
#     { github = "https://github.com/username" },
#     { instagram = "https://instagram.com/username" },
     { linkedin = "https://it.linkedin.com/in/michele-cannarsa-7687348b" },
     { telegram = "https://t.me/+393490867235" },
#     { x-twitter = "https://twitter.com/username" },
     { whatsapp = "https://wa.me/+393490867235" },
   ]
